"""removed move from TeamMember and replaced with Pokemon, also added item

Revision ID: 0ad6f2aeb083
Revises: e6f54f1532a1
Create Date: 2024-08-13 10:42:30.381785

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0ad6f2aeb083'
down_revision: str | None = 'e6f54f1532a1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
