"""initial migration

Revision ID: 8d9d0e20dd0a
Revises: 
Create Date: 2024-08-12 16:53:08.082528

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d9d0e20dd0a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moves',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('move_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('power', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('accuracy', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('atk', sa.Integer(), nullable=False),
    sa.Column('def_', sa.Integer(), nullable=False),
    sa.Column('spa', sa.Integer(), nullable=False),
    sa.Column('spd', sa.Integer(), nullable=False),
    sa.Column('spe', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pokemon',
    sa.Column('natdex_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pokemon_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('abilities', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_stats_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['base_stats_id'], ['stats.id'], ),
    sa.PrimaryKeyConstraint('natdex_id')
    )
    op.create_index(op.f('ix_pokemon_name'), 'pokemon', ['name'], unique=True)
    op.create_table('links',
    sa.Column('pokemon_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('move_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['move_name'], ['moves.name'], ),
    sa.ForeignKeyConstraint(['pokemon_name'], ['pokemon.name'], ),
    sa.PrimaryKeyConstraint('pokemon_name', 'move_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links')
    op.drop_index(op.f('ix_pokemon_name'), table_name='pokemon')
    op.drop_table('pokemon')
    op.drop_table('stats')
    op.drop_table('moves')
    op.drop_table('items')
    # ### end Alembic commands ###
