"""modified TeamMemberResponse so ability is optional

Revision ID: a25792002d38
Revises: c3d0ff0d5c82
Create Date: 2024-08-14 09:52:21.247356

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a25792002d38'
down_revision: str | None = 'c3d0ff0d5c82'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
