"""removed stats from TeamMemberResponse

Revision ID: bc940f9dd531
Revises: c976ea72c132
Create Date: 2024-08-13 16:03:29.349150

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bc940f9dd531'
down_revision: str | None = 'c976ea72c132'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('ability', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_members', 'ability')
    # ### end Alembic commands ###
