"""added response model for TeamMember and Teams

Revision ID: c819d0046595
Revises: 0ab5b35b680a
Create Date: 2024-08-13 15:24:13.678660

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c819d0046595'
down_revision: str | None = '0ab5b35b680a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
