"""modified TeamMember model with moves and removed request models

Revision ID: e6f54f1532a1
Revises: a86ed699af1c
Create Date: 2024-08-13 10:15:48.537736

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e6f54f1532a1'
down_revision: str | None = 'a86ed699af1c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
